package com.example.kbawelfaremessenger

import android.app.DatePickerDialog
import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONArray
import org.json.JSONObject
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.concurrent.Executors

class AdvocateDiaryActivity : AppCompatActivity() {
    private val fmt=DateTimeFormatter.ofPattern("dd-MM-yyyy")
    private val prefsName="advocate_diary"; private val keyEntries="entries"
    private lateinit var date:EditText; private lateinit var title:EditText; private lateinit var court:EditText; private lateinit var caseNumber:EditText; private lateinit var client:EditText
    private lateinit var previousDate:EditText; private lateinit var nextDate:EditText; private lateinit var remark:EditText; private lateinit var list:LinearLayout; private lateinit var causeList:LinearLayout; private lateinit var causeHeader:TextView
    private var editingId:Long?=null; private val executor=Executors.newSingleThreadExecutor(); private var closed=false

    override fun onCreate(savedInstanceState:Bundle?) {
        super.onCreate(savedInstanceState)
        if(!LicenseManager.isFeatureEnabled(this,"advocate_diary")){Toast.makeText(this,"Advocate Diary is not enabled in this license.",Toast.LENGTH_LONG).show();finish();return}
        setContentView(R.layout.activity_advocate_diary);supportActionBar?.title="Advocate Diary";supportActionBar?.setDisplayHomeAsUpEnabled(true)
        date=findViewById(R.id.diaryDate);title=findViewById(R.id.diaryTitle);court=findViewById(R.id.diaryCourt);caseNumber=findViewById(R.id.diaryCaseNumber);client=findViewById(R.id.diaryClient);previousDate=findViewById(R.id.diaryPreviousDate);nextDate=findViewById(R.id.diaryNextDate);remark=findViewById(R.id.diaryRemark);list=findViewById(R.id.diaryList);causeList=findViewById(R.id.causeList);causeHeader=findViewById(R.id.causeListHeader)
        date.setText(LocalDate.now().format(fmt));date.setOnClickListener{pick(date){showCauseList()}};nextDate.setOnClickListener{pick(nextDate)}
        findViewById<Button>(R.id.btnFetchHelper).setOnClickListener{fetchFromHelper()};findViewById<Button>(R.id.btnCheckCauseList).setOnClickListener{showCauseList()};findViewById<Button>(R.id.diarySave).setOnClickListener{saveEntry()};findViewById<Button>(R.id.diaryClear).setOnClickListener{clearForm()}
        val fromIntent=intent.getStringExtra("case_number")?.trim().orEmpty();if(fromIntent.isNotEmpty()){caseNumber.setText(fromIntent);fetchFromHelper()};renderEntries();showCauseList()
    }
    private fun pick(target:EditText,after:(()->Unit)?=null){val d=runCatching{LocalDate.parse(target.text.toString(),fmt)}.getOrDefault(LocalDate.now());DatePickerDialog(this,{_,y,m,day->target.setText(LocalDate.of(y,m+1,day).format(fmt));after?.invoke()},d.year,d.monthValue-1,d.dayOfMonth).show()}
    private fun fetchFromHelper(){val cn=caseNumber.text.toString().trim();if(cn.isEmpty()){caseNumber.error="Enter case number";return};executor.execute{val db=AdvocateCaseDbHelper(this);val item=db.getCaseByCaseNumber(cn);db.close();runOnUiThread{if(closed)return@runOnUiThread;if(item==null){Toast.makeText(this,"Case not found in Advocate Helper.",Toast.LENGTH_SHORT).show();return@runOnUiThread};client.setText(item.clientName);court.setText(item.courtName);previousDate.setText(item.currentDate.ifBlank{item.previousDate});nextDate.setText(item.nextDate);if(title.text.toString().isBlank())title.setText("Hearing - ${item.caseNumber}");Toast.makeText(this,"Case details fetched from Advocate Helper.",Toast.LENGTH_SHORT).show()}}}
    private fun saveEntry(){val cn=caseNumber.text.toString().trim();val t=title.text.toString().trim();val d=runCatching{LocalDate.parse(date.text.toString(),fmt)}.getOrNull();if(cn.isBlank()){caseNumber.error="Enter case number";return};if(t.isBlank()){title.error="Enter hearing/activity";return};if(d==null){date.error="Select date";return};val entries=readEntries();val obj=if(editingId!=null)find(entries,editingId!!)?:JSONObject()else JSONObject();val id=editingId?:System.currentTimeMillis();obj.put("id",id).put("date",d.format(fmt)).put("title",t).put("court",court.text.toString().trim()).put("caseNumber",cn).put("client",client.text.toString().trim()).put("previousDate",previousDate.text.toString().trim()).put("nextDate",nextDate.text.toString().trim()).put("remark",remark.text.toString().trim()).put("notes",remark.text.toString().trim());if(editingId==null)entries.put(obj);saveEntries(entries);syncHelperCase(cn,d.format(fmt),nextDate.text.toString().trim(),remark.text.toString().trim());AppLogger.success(this,"DIARY",if(editingId==null)"Diary entry created"else"Diary entry updated");Toast.makeText(this,if(editingId==null)"Diary entry saved"else"Diary entry updated",Toast.LENGTH_SHORT).show();clearForm();renderEntries();showCauseList()}
    private fun syncHelperCase(cn:String,hearingDate:String,newNextDate:String,newRemark:String){executor.execute{val db=AdvocateCaseDbHelper(this);val item=db.getCaseByCaseNumber(cn);if(item!=null){db.updateCase(item.copy(previousDate=item.currentDate.ifBlank{item.previousDate},currentDate=hearingDate,nextDate=newNextDate,currentUpdate=item.newUpdate,newUpdate=newRemark,updatedAt=System.currentTimeMillis()))};db.close()}}
    private fun showCauseList(){val selected=date.text.toString().trim();causeList.removeAllViews();causeHeader.text="CAUSE LIST • $selected";executor.execute{val db=AdvocateCaseDbHelper(this);val rows=db.getAllCases().filter{it.nextDate==selected};db.close();runOnUiThread{if(closed)return@runOnUiThread;if(rows.isEmpty())causeList.addView(TextView(this).apply{text="No causes listed for this date.";setPadding(8,12,8,12)})else rows.forEach{item->causeList.addView(TextView(this).apply{text="${item.caseNumber}  •  ${item.clientName}\n${item.courtName.ifBlank{"Court not specified"}}  •  Next: ${item.nextDate}";setPadding(8,10,8,10);setOnClickListener{caseNumber.setText(item.caseNumber);fetchFromHelper()}})}}}}
    private fun renderEntries(){list.removeAllViews();val rows=mutableListOf<JSONObject>();val entries=readEntries();for(i in 0 until entries.length())entries.optJSONObject(i)?.let(rows::add);rows.sortByDescending{it.optString("date")+it.optLong("id").toString().padStart(16,'0')};if(rows.isEmpty()){list.addView(TextView(this).apply{text="No diary entries yet.";setPadding(8,16,8,16)});return};rows.forEach{e->val card=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(12,10,12,10)};val head=TextView(this).apply{text="${e.optString("date")}  •  ${e.optString("title")}";textSize=17f;setTypeface(null,1)};val detail=TextView(this).apply{text=listOf("Case: ${e.optString("caseNumber")}","Client: ${e.optString("client")}",e.optString("court").takeIf{it.isNotBlank()}?.let{"Court: $it"},"Previous Date: ${e.optString("previousDate")}","Next Date: ${e.optString("nextDate")}",e.optString("remark").takeIf{it.isNotBlank()}?.let{"Remark: $it"}).filterNotNull().joinToString("\n");setPadding(0,6,0,6)};val actions=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};actions.addView(Button(this@AdvocateDiaryActivity).apply{text="EDIT";setOnClickListener{load(e)}},LinearLayout.LayoutParams(0,-2,1f));actions.addView(Button(this@AdvocateDiaryActivity).apply{text="DELETE";setOnClickListener{delete(e.optLong("id"))}},LinearLayout.LayoutParams(0,-2,1f));card.addView(head);card.addView(detail);card.addView(actions);list.addView(card);list.addView(View(this).apply{minimumHeight=8})}}
    private fun load(e:JSONObject){editingId=e.optLong("id");date.setText(e.optString("date"));title.setText(e.optString("title"));court.setText(e.optString("court"));caseNumber.setText(e.optString("caseNumber"));client.setText(e.optString("client"));previousDate.setText(e.optString("previousDate"));nextDate.setText(e.optString("nextDate"));remark.setText(e.optString("remark",e.optString("notes")));findViewById<Button>(R.id.diarySave).text="UPDATE ENTRY";findViewById<Button>(R.id.diaryClear).text="CANCEL EDIT";findViewById<ScrollView>(R.id.diaryScroll).post{findViewById<ScrollView>(R.id.diaryScroll).smoothScrollTo(0,0)}}
    private fun delete(id:Long){AlertDialog.Builder(this).setTitle("Delete diary entry?").setMessage("This entry will be permanently removed from this device.").setNegativeButton("CANCEL",null).setPositiveButton("DELETE"){_,_->val entries=readEntries();for(i in entries.length()-1 downTo 0)if(entries.optJSONObject(i)?.optLong("id")==id)entries.remove(i);saveEntries(entries);AppLogger.info(this,"DIARY","Diary entry deleted");renderEntries()}.show()}
    private fun clearForm(){editingId=null;date.setText(LocalDate.now().format(fmt));title.text.clear();court.text.clear();caseNumber.text.clear();client.text.clear();previousDate.text.clear();nextDate.text.clear();remark.text.clear();findViewById<Button>(R.id.diarySave).text="SAVE ENTRY";findViewById<Button>(R.id.diaryClear).text="CLEAR"}
    private fun readEntries():JSONArray=runCatching{JSONArray(getSharedPreferences(prefsName,0).getString(keyEntries,"[]"))}.getOrDefault(JSONArray())
    private fun saveEntries(a:JSONArray){getSharedPreferences(prefsName,0).edit().putString(keyEntries,a.toString()).apply()}
    private fun find(a:JSONArray,id:Long):JSONObject?{for(i in 0 until a.length())if(a.optJSONObject(i)?.optLong("id")==id)return a.optJSONObject(i);return null}
    override fun onSupportNavigateUp():Boolean{finish();return true};override fun onDestroy(){closed=true;executor.shutdownNow();super.onDestroy()}
}
