package com.example.kbawelfaremessenger

import android.app.DatePickerDialog
import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONArray
import org.json.JSONObject
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.concurrent.Executors

class AdvocateDiaryActivity : AppCompatActivity() {
    private val fmt=DateTimeFormatter.ofPattern("dd-MM-yyyy")
    private val prefs="advocate_diary"; private val key="entries"
    private lateinit var date:EditText; private lateinit var title:EditText; private lateinit var caseNo:EditText; private lateinit var client:EditText; private lateinit var court:EditText; private lateinit var previous:EditText; private lateinit var next:EditText; private lateinit var remark:EditText; private lateinit var list:LinearLayout; private lateinit var causes:LinearLayout; private lateinit var causeHeader:TextView
    private var editId:Long?=null; private val executor=Executors.newSingleThreadExecutor(); private var closed=false

    override fun onCreate(state:Bundle?){super.onCreate(state);if(!LicenseManager.isFeatureEnabled(this,"advocate_diary")){Toast.makeText(this,"Advocate Diary is not enabled in this license.",Toast.LENGTH_LONG).show();finish();return};setContentView(R.layout.activity_advocate_diary);supportActionBar?.title="Advocate Diary";supportActionBar?.setDisplayHomeAsUpEnabled(true)
        date=findViewById(R.id.diaryDate);title=findViewById(R.id.diaryTitle);caseNo=findViewById(R.id.diaryCaseNumber);client=findViewById(R.id.diaryClient);court=findViewById(R.id.diaryCourt);previous=findViewById(R.id.diaryPreviousDate);next=findViewById(R.id.diaryNextDate);remark=findViewById(R.id.diaryRemark);list=findViewById(R.id.diaryList);causes=findViewById(R.id.causeList);causeHeader=findViewById(R.id.causeListHeader)
        date.setText(LocalDate.now().format(fmt));date.setOnClickListener{pick(date){showCauseList()}};next.setOnClickListener{pick(next)};findViewById<Button>(R.id.btnFetchHelper).setOnClickListener{fetchHelper()};findViewById<Button>(R.id.btnCheckCauseList).setOnClickListener{showCauseList()};findViewById<Button>(R.id.diarySave).setOnClickListener{save()};findViewById<Button>(R.id.diaryClear).setOnClickListener{clear()};setupCollapse()
        intent.getStringExtra("case_number")?.trim()?.takeIf{it.isNotEmpty()}?.let{caseNo.setText(it);fetchHelper()};render();showCauseList()
    }
    private fun setupCollapse(){listOf(R.id.headerHearing to R.id.sectionHearing,R.id.headerCase to R.id.sectionCase,R.id.headerUpdate to R.id.sectionUpdate,R.id.headerSaved to R.id.sectionSaved).forEach{(h,s)->val a=findViewById<TextView>(h);val v=findViewById<View>(s);a.setOnClickListener{v.visibility=if(v.visibility==View.VISIBLE)View.GONE else View.VISIBLE}}}
    private fun pick(target:EditText,after:(()->Unit)?=null){val d=runCatching{LocalDate.parse(target.text.toString(),fmt)}.getOrDefault(LocalDate.now());DatePickerDialog(this,{_,y,m,day->target.setText(LocalDate.of(y,m+1,day).format(fmt));after?.invoke()},d.year,d.monthValue-1,d.dayOfMonth).show()}
    private fun fetchHelper(){val n=caseNo.text.toString().trim();if(n.isEmpty()){caseNo.error="Enter case number";return};executor.execute{val db=AdvocateCaseDbHelper(this);val x=db.getCaseByCaseNumber(n);db.close();runOnUiThread{if(closed)return@runOnUiThread;if(x==null){Toast.makeText(this,"Case not found in Advocate Helper.",Toast.LENGTH_SHORT).show()}else{client.setText(x.clientName);court.setText(x.courtName);previous.setText(x.currentDate.ifBlank{x.previousDate});next.setText(x.nextDate);if(title.text.isBlank())title.setText("Hearing - ${x.caseNumber}")}}}}
    private fun save(){val n=caseNo.text.toString().trim();val t=title.text.toString().trim();val d=runCatching{LocalDate.parse(date.text.toString(),fmt)}.getOrNull();if(n.isEmpty()){caseNo.error="Enter case number";return};if(t.isEmpty()){title.error="Enter hearing/activity";return};if(d==null){date.error="Select date";return};val a=read();val o=if(editId==null)JSONObject()else find(a,editId!!)?:JSONObject();val id=editId?:System.currentTimeMillis();o.put("id",id).put("date",d.format(fmt)).put("title",t).put("caseNumber",n).put("client",client.text.toString().trim()).put("court",court.text.toString().trim()).put("previousDate",previous.text.toString().trim()).put("nextDate",next.text.toString().trim()).put("remark",remark.text.toString().trim()).put("notes",remark.text.toString().trim());if(editId==null)a.put(o);write(a);sync(n,d.format(fmt),next.text.toString().trim(),remark.text.toString().trim());AppLogger.success(this,"DIARY",if(editId==null)"Diary entry created"else"Diary entry updated");Toast.makeText(this,if(editId==null)"Diary entry saved"else"Diary entry updated",Toast.LENGTH_SHORT).show();clear();render();showCauseList()}
    private fun sync(n:String,hearing:String,nextDate:String,r:String){executor.execute{val db=AdvocateCaseDbHelper(this);db.getCaseByCaseNumber(n)?.let{x->db.updateCase(x.copy(previousDate=x.currentDate.ifBlank{x.previousDate},currentDate=hearing,nextDate=nextDate,currentUpdate=x.newUpdate,newUpdate=r,updatedAt=System.currentTimeMillis()))};db.close()}}
    private fun showCauseList(){val d=date.text.toString().trim();causeHeader.text="CAUSE LIST • $d";causes.removeAllViews();executor.execute{val db=AdvocateCaseDbHelper(this);val rows=db.getAllCases().filter{it.nextDate==d};db.close();runOnUiThread{if(closed)return@runOnUiThread;if(rows.isEmpty())causes.addView(TextView(this).apply{text="No causes listed for this date.";setPadding(8,10,8,10)})else rows.forEach{x->causes.addView(TextView(this).apply{text="${x.caseNumber} • ${x.clientName}\n${x.courtName.ifBlank{"Court not specified"}}";setPadding(8,10,8,10);setOnClickListener{caseNo.setText(x.caseNumber);fetchHelper()}})}}}}
    private fun render(){list.removeAllViews();val rows=mutableListOf<JSONObject>();val a=read();for(i in 0 until a.length())a.optJSONObject(i)?.let(rows::add);rows.sortByDescending{it.optString("date")+it.optLong("id")};if(rows.isEmpty()){list.addView(TextView(this).apply{text="No diary entries yet.";setPadding(8,12,8,12)});return};rows.forEach{x->val card=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(10,8,10,8)};card.addView(TextView(this).apply{text="${x.optString("date")} • ${x.optString("title")}";textSize=17f;setTypeface(null,1)});card.addView(TextView(this).apply{text="Case: ${x.optString("caseNumber")}\nClient: ${x.optString("client")}\nCourt: ${x.optString("court")}\nPrevious: ${x.optString("previousDate")}\nNext: ${x.optString("nextDate")}\nRemark: ${x.optString("remark",x.optString("notes"))}"});val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};row.addView(Button(this@AdvocateDiaryActivity).apply{text="EDIT";setOnClickListener{load(x)}},LinearLayout.LayoutParams(0,-2,1f));row.addView(Button(this@AdvocateDiaryActivity).apply{text="DELETE";setOnClickListener{delete(x.optLong("id"))}},LinearLayout.LayoutParams(0,-2,1f));card.addView(row);list.addView(card)}}
    private fun load(x:JSONObject){editId=x.optLong("id");date.setText(x.optString("date"));title.setText(x.optString("title"));caseNo.setText(x.optString("caseNumber"));client.setText(x.optString("client"));court.setText(x.optString("court"));previous.setText(x.optString("previousDate"));next.setText(x.optString("nextDate"));remark.setText(x.optString("remark",x.optString("notes")));findViewById<Button>(R.id.diarySave).text="UPDATE ENTRY";findViewById<Button>(R.id.diaryClear).text="CANCEL EDIT";findViewById<ScrollView>(R.id.diaryScroll).post{findViewById<ScrollView>(R.id.diaryScroll).smoothScrollTo(0,0)}}
    private fun delete(id:Long){AlertDialog.Builder(this).setTitle("Delete diary entry?").setNegativeButton("CANCEL",null).setPositiveButton("DELETE"){_,_->val a=read();for(i in a.length()-1 downTo 0)if(a.optJSONObject(i)?.optLong("id")==id)a.remove(i);write(a);AppLogger.info(this,"DIARY","Diary entry deleted");render()}.show()}
    private fun clear(){editId=null;date.setText(LocalDate.now().format(fmt));title.text.clear();caseNo.text.clear();client.text.clear();court.text.clear();previous.text.clear();next.text.clear();remark.text.clear();findViewById<Button>(R.id.diarySave).text="SAVE ENTRY";findViewById<Button>(R.id.diaryClear).text="CLEAR"}
    private fun read():JSONArray=runCatching{JSONArray(getSharedPreferences(prefs,0).getString(key,"[]"))}.getOrDefault(JSONArray())
    private fun write(a:JSONArray){getSharedPreferences(prefs,0).edit().putString(key,a.toString()).apply()}
    private fun find(a:JSONArray,id:Long):JSONObject?{for(i in 0 until a.length())if(a.optJSONObject(i)?.optLong("id")==id)return a.optJSONObject(i);return null}
    override fun onSupportNavigateUp():Boolean{finish();return true};override fun onDestroy(){closed=true;executor.shutdownNow();super.onDestroy()}
}
