name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      - name: Build signed release APK
        run: ./gradlew assembleRelease

      - name: Upload MyAdv APK
        uses: actions/upload-artifact@v4
        with:
          name: MyAdv-release-v2.1
          path: app/build/outputs/apk/release/*.apk
